name: Terraform

on:
  push:
    branches: [ main ]
    paths: [ "infra/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "infra/**" ]

permissions:
  id-token: write   # needed for OIDC
  contents: read

env:
  TF_WORKING_DIR: infra
  AWS_REGION: ${{ secrets.AWS_REGION }}   # e.g., us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
